(cl:in-package RosAdapter-msg)
(cl:export '(U8DIST-VAL
          U8DIST
          U8NEARESTDIST-VAL
          U8NEARESTDIST
          U8TRAFFICSIGNDISTX-VAL
          U8TRAFFICSIGNDISTX
          U8TRAFFICSIGNDISTY-VAL
          U8TRAFFICSIGNDISTY
          SSENSORPOS-VAL
          SSENSORPOS
          SNEARESTSENSORPOS-VAL
          SNEARESTSENSORPOS
          U1TRAFFICSIGNTYPE-VAL
          U1TRAFFICSIGNTYPE
))