(cl:in-package RosAdapter-msg)
(cl:export '(SPOS-VAL
          SPOS
          SORIGINCOORDSYS-VAL
          SORIGINCOORDSYS
          AU1NAME-VAL
          AU1NAME
          U8HOSTID-VAL
          U8HOSTID
          U8ID-VAL
          U8ID
          AU4FOVHV-VAL
          AU4FOVHV
          AU4CLIPNF-VAL
          AU4CLIPNF
          AU4FOVOFFHV-VAL
          AU4FOVOFFHV
          U1TYPE-VAL
          U1TYPE
          U1MODELTYPE-VAL
          U1MODELTYPE
          U4IDEALFREQ-VAL
          U4IDEALFREQ
          U4RESL-VAL
          U4RESL
          U4RESV-VAL
          U4RESV
          U4SENSIZEL-VAL
          U4SENSIZEL
          U4SENSIZEW-VAL
          U4SENSIZEW
          U4LENFD-VAL
          U4LENFD
          U4DISTCENL-VAL
          U4DISTCENL
          U4DISTCENW-VAL
          U4DISTCENW
          U4DISTPARK1-VAL
          U4DISTPARK1
          U4DISTPARK2-VAL
          U4DISTPARK2
))