(cl:in-package RosAdapter-msg)
(cl:export '(U8RAININTENSITY-VAL
          U8RAININTENSITY
          U8SNOWINTENSITY-VAL
          U8SNOWINTENSITY
          U8FOGINTENSITY-VAL
          U8FOGINTENSITY
          U8FOGVISUALRANGE-VAL
          U8FOGVISUALRANGE
          U4TIMEOFDAY-VAL
          U4TIMEOFDAY
          U2TIMEZONEMINUTESWEST-VAL
          U2TIMEZONEMINUTESWEST
          U2YEAR-VAL
          U2YEAR
          U1CLOUDSTATE-VAL
          U1CLOUDSTATE
          U1DAY-VAL
          U1DAY
          U1MONTH-VAL
          U1MONTH
))