(cl:in-package RosAdapter-msg)
(cl:export '(STARTCHAR-VAL
          STARTCHAR
          CMD-VAL
          CMD
          MTIME-VAL
          MTIME
          LAT-VAL
          LAT
          NORS-VAL
          NORS
          LON-VAL
          LON
          EORW-VAL
          EORW
          MODE-VAL
          MODE
          COUNT-VAL
          COUNT
          HORIZONPRECIOUS-VAL
          HORIZONPRECIOUS
          GEOIDALHEIGHT-VAL
          GEOIDALHEIGHT
          METER1-VAL
          METER1
          HEIGHT-VAL
          HEIGHT
          METER2-VAL
          METER2
          DATAAGE-VAL
          DATAAGE
          BASESTATIONFLAG-VAL
          BASESTATIONFLAG
          SPERATOR-VAL
          SPERATOR
          CHECKSUM-VAL
          CHECKSUM
))