(cl:in-package RosAdapter-msg)
(cl:export '(U8THROTTLEVALUE-VAL
          U8THROTTLEVALUE
          U8BRAKEVALUE-VAL
          U8BRAKEVALUE
          U8STEERINGWHEELVALUE-VAL
          U8STEERINGWHEELVALUE
          U8PARKINGBRAKEVALUE-VAL
          U8PARKINGBRAKEVALUE
          U8CLUTCHVALUE-VAL
          U8CLUTCHVALUE
          U8GEARVALUE-VAL
          U8GEARVALUE
          U4OBJECTID-VAL
          U4OBJECTID
          U1THROTTLEACTIVE-VAL
          U1THROTTLEACTIVE
          U1BRAKEACTIVE-VAL
          U1BRAKEACTIVE
          U1STEERINGWHEELACTIVE-VAL
          U1STEERINGWHEELACTIVE
          U1PARKINGBRAKEACTIVE-VAL
          U1PARKINGBRAKEACTIVE
          U1CLUTCHACTIVE-VAL
          U1CLUTCHACTIVE
          U1GEARACTIVE-VAL
          U1GEARACTIVE
))