(cl:in-package RosAdapter-msg)
(cl:export '(SSPEED-VAL
          SSPEED
          SACCEL-VAL
          SACCEL
          SGEO-VAL
          SGEO
          SPOS-VAL
          SPOS
          AU1NAME-VAL
          AU1NAME
          AU1MODELFILENAME-VAL
          AU1MODELFILENAME
          AU1MODELNAME-VAL
          AU1MODELNAME
          AU8PARAMSCALE-VAL
          AU8PARAMSCALE
          U8ROADID-VAL
          U8ROADID
          U8SPEEDLIMIT-VAL
          U8SPEEDLIMIT
          U4ID-VAL
          U4ID
          U4ROADS-VAL
          U4ROADS
          U4ROADT-VAL
          U4ROADT
          U4HDGREL-VAL
          U4HDGREL
          U4LANEOFFSET-VAL
          U4LANEOFFSET
          U4TRAVELEDDIST-VAL
          U4TRAVELEDDIST
          U2VISMASK-VAL
          U2VISMASK
          U1TYPE-VAL
          U1TYPE
          U1LANEID-VAL
          U1LANEID
          U1DIR-VAL
          U1DIR
          U1ISONROAD-VAL
          U1ISONROAD
          U1CATEGORY-VAL
          U1CATEGORY
))