(cl:in-package RosAdapter-msg)
(cl:export '(U4LIGHTMASK-VAL
          U4LIGHTMASK
          U4DISTANCEX-VAL
          U4DISTANCEX
          U4DISTANCEY-VAL
          U4DISTANCEY
          U4VELOCITYX-VAL
          U4VELOCITYX
          U4VELOCITYY-VAL
          U4VELOCITYY
          U4ACCELERATIONX-VAL
          U4ACCELERATIONX
          U4ACCELERATIONY-VAL
          U4ACCELERATIONY
          U4YAWRATE-VAL
          U4YAWRATE
          U4DIST-VAL
          U4DIST
          U4ANGLE-VAL
          U4ANGLE
          U1OBJCLASS-VAL
          U1OBJCLASS
          U1FLAG_DETECTED-VAL
          U1FLAG_DETECTED
          U1MOVABLE-VAL
          U1MOVABLE
          U1MOVING-VAL
          U1MOVING
          U1OBJ_AGE-VAL
          U1OBJ_AGE
))