(cl:in-package RosAdapter-msg)
(cl:export '(U8ROADID-VAL
          U8ROADID
          CURVVERT-VAL
          CURVVERT
          U4STARTDX-VAL
          U4STARTDX
          U4WIDTH-VAL
          U4WIDTH
          U4VIEWRANGESTART-VAL
          U4VIEWRANGESTART
          U4VIEWRANGEEND-VAL
          U4VIEWRANGEEND
          U4MEASUREDVREND-VAL
          U4MEASUREDVREND
          U4C0-VAL
          U4C0
          U4C1-VAL
          U4C1
          U4C2-VAL
          U4C2
          U4C3-VAL
          U4C3
          U2LANECHANGE-VAL
          U2LANECHANGE
          U1LANEID-VAL
          U1LANEID
          U1QUALITY-VAL
          U1QUALITY
          U1TYPE-VAL
          U1TYPE
          U1COLOR-VAL
          U1COLOR
          U1LEFTCROSSING-VAL
          U1LEFTCROSSING
          U1RIGHTCROSSING-VAL
          U1RIGHTCROSSING
))