; Auto-generated. Do not edit!


(cl:in-package RosAdapter-msg)


;//! \htmlinclude rosSimproToAD.msg.html

(cl:defclass <rosSimproToAD> (roslisp-msg-protocol:ros-message)
  ((head
    :reader head
    :initarg :head
    :type RosAdapter-msg:header
    :initform (cl:make-instance 'RosAdapter-msg:header))
   (laneInfos
    :reader laneInfos
    :initarg :laneInfos
    :type (cl:vector RosAdapter-msg:lane_info)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:lane_info :initial-element (cl:make-instance 'RosAdapter-msg:lane_info)))
   (sensorStates
    :reader sensorStates
    :initarg :sensorStates
    :type (cl:vector RosAdapter-msg:sensor_info)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:sensor_info :initial-element (cl:make-instance 'RosAdapter-msg:sensor_info)))
   (sensorObjects
    :reader sensorObjects
    :initarg :sensorObjects
    :type (cl:vector RosAdapter-msg:sensor_detection_info)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:sensor_detection_info :initial-element (cl:make-instance 'RosAdapter-msg:sensor_detection_info)))
   (contactPoints
    :reader contactPoints
    :initarg :contactPoints
    :type (cl:vector RosAdapter-msg:contact_point)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:contact_point :initial-element (cl:make-instance 'RosAdapter-msg:contact_point)))
   (trafficSigns
    :reader trafficSigns
    :initarg :trafficSigns
    :type (cl:vector RosAdapter-msg:traffic_sign)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:traffic_sign :initial-element (cl:make-instance 'RosAdapter-msg:traffic_sign)))
   (roadStates
    :reader roadStates
    :initarg :roadStates
    :type (cl:vector RosAdapter-msg:road_state)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:road_state :initial-element (cl:make-instance 'RosAdapter-msg:road_state)))
   (environments
    :reader environments
    :initarg :environments
    :type (cl:vector RosAdapter-msg:environment)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:environment :initial-element (cl:make-instance 'RosAdapter-msg:environment)))
   (trafficLights
    :reader trafficLights
    :initarg :trafficLights
    :type (cl:vector RosAdapter-msg:traffic_light)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:traffic_light :initial-element (cl:make-instance 'RosAdapter-msg:traffic_light)))
   (roadQueries
    :reader roadQueries
    :initarg :roadQueries
    :type (cl:vector RosAdapter-msg:road_query)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:road_query :initial-element (cl:make-instance 'RosAdapter-msg:road_query)))
   (egoStates
    :reader egoStates
    :initarg :egoStates
    :type (cl:vector RosAdapter-msg:mil_ego_state)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:mil_ego_state :initial-element (cl:make-instance 'RosAdapter-msg:mil_ego_state)))
   (milObjStates
    :reader milObjStates
    :initarg :milObjStates
    :type (cl:vector RosAdapter-msg:mil_object_state)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:mil_object_state :initial-element (cl:make-instance 'RosAdapter-msg:mil_object_state)))
   (milRoadMarks
    :reader milRoadMarks
    :initarg :milRoadMarks
    :type (cl:vector RosAdapter-msg:mil_roadmark)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:mil_roadmark :initial-element (cl:make-instance 'RosAdapter-msg:mil_roadmark)))
   (initParams
    :reader initParams
    :initarg :initParams
    :type (cl:vector RosAdapter-msg:init_param)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:init_param :initial-element (cl:make-instance 'RosAdapter-msg:init_param)))
   (milAmesimSignals
    :reader milAmesimSignals
    :initarg :milAmesimSignals
    :type (cl:vector RosAdapter-msg:mil_amesim_signal)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:mil_amesim_signal :initial-element (cl:make-instance 'RosAdapter-msg:mil_amesim_signal)))
   (activateControllers
    :reader activateControllers
    :initarg :activateControllers
    :type (cl:vector RosAdapter-msg:activate_controller)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:activate_controller :initial-element (cl:make-instance 'RosAdapter-msg:activate_controller)))
   (assignControllers
    :reader assignControllers
    :initarg :assignControllers
    :type (cl:vector RosAdapter-msg:assign_controller)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:assign_controller :initial-element (cl:make-instance 'RosAdapter-msg:assign_controller)))
   (overrideControllers
    :reader overrideControllers
    :initarg :overrideControllers
    :type (cl:vector RosAdapter-msg:override_controller)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:override_controller :initial-element (cl:make-instance 'RosAdapter-msg:override_controller)))
   (customCommands
    :reader customCommands
    :initarg :customCommands
    :type (cl:vector RosAdapter-msg:custom_command)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:custom_command :initial-element (cl:make-instance 'RosAdapter-msg:custom_command)))
   (parkingSpaces
    :reader parkingSpaces
    :initarg :parkingSpaces
    :type (cl:vector RosAdapter-msg:parkingSpace)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:parkingSpace :initial-element (cl:make-instance 'RosAdapter-msg:parkingSpace)))
   (driverCtrls
    :reader driverCtrls
    :initarg :driverCtrls
    :type (cl:vector RosAdapter-msg:driver_ctrl)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:driver_ctrl :initial-element (cl:make-instance 'RosAdapter-msg:driver_ctrl)))
   (syncs
    :reader syncs
    :initarg :syncs
    :type (cl:vector RosAdapter-msg:sync)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:sync :initial-element (cl:make-instance 'RosAdapter-msg:sync)))
   (imuDatas
    :reader imuDatas
    :initarg :imuDatas
    :type (cl:vector RosAdapter-msg:imu_data)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:imu_data :initial-element (cl:make-instance 'RosAdapter-msg:imu_data)))
   (gnssGgaS
    :reader gnssGgaS
    :initarg :gnssGgaS
    :type (cl:vector RosAdapter-msg:gnss_gga)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:gnss_gga :initial-element (cl:make-instance 'RosAdapter-msg:gnss_gga)))
   (uwbDatas
    :reader uwbDatas
    :initarg :uwbDatas
    :type (cl:vector RosAdapter-msg:uwb_data)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:uwb_data :initial-element (cl:make-instance 'RosAdapter-msg:uwb_data)))
   (modelOutlines
    :reader modelOutlines
    :initarg :modelOutlines
    :type (cl:vector RosAdapter-msg:model_outline)
   :initform (cl:make-array 0 :element-type 'RosAdapter-msg:model_outline :initial-element (cl:make-instance 'RosAdapter-msg:model_outline)))
   (rsuVnfpInfo
    :reader rsuVnfpInfo
    :initarg :rsuVnfpInfo
    :type RosAdapter-msg:rsu_vnfp_info
    :initform (cl:make-instance 'RosAdapter-msg:rsu_vnfp_info)))
)

(cl:defclass rosSimproToAD (<rosSimproToAD>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <rosSimproToAD>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'rosSimproToAD)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name RosAdapter-msg:<rosSimproToAD> is deprecated: use RosAdapter-msg:rosSimproToAD instead.")))

(cl:ensure-generic-function 'head-val :lambda-list '(m))
(cl:defmethod head-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:head-val is deprecated.  Use RosAdapter-msg:head instead.")
  (head m))

(cl:ensure-generic-function 'laneInfos-val :lambda-list '(m))
(cl:defmethod laneInfos-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:laneInfos-val is deprecated.  Use RosAdapter-msg:laneInfos instead.")
  (laneInfos m))

(cl:ensure-generic-function 'sensorStates-val :lambda-list '(m))
(cl:defmethod sensorStates-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:sensorStates-val is deprecated.  Use RosAdapter-msg:sensorStates instead.")
  (sensorStates m))

(cl:ensure-generic-function 'sensorObjects-val :lambda-list '(m))
(cl:defmethod sensorObjects-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:sensorObjects-val is deprecated.  Use RosAdapter-msg:sensorObjects instead.")
  (sensorObjects m))

(cl:ensure-generic-function 'contactPoints-val :lambda-list '(m))
(cl:defmethod contactPoints-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:contactPoints-val is deprecated.  Use RosAdapter-msg:contactPoints instead.")
  (contactPoints m))

(cl:ensure-generic-function 'trafficSigns-val :lambda-list '(m))
(cl:defmethod trafficSigns-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:trafficSigns-val is deprecated.  Use RosAdapter-msg:trafficSigns instead.")
  (trafficSigns m))

(cl:ensure-generic-function 'roadStates-val :lambda-list '(m))
(cl:defmethod roadStates-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:roadStates-val is deprecated.  Use RosAdapter-msg:roadStates instead.")
  (roadStates m))

(cl:ensure-generic-function 'environments-val :lambda-list '(m))
(cl:defmethod environments-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:environments-val is deprecated.  Use RosAdapter-msg:environments instead.")
  (environments m))

(cl:ensure-generic-function 'trafficLights-val :lambda-list '(m))
(cl:defmethod trafficLights-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:trafficLights-val is deprecated.  Use RosAdapter-msg:trafficLights instead.")
  (trafficLights m))

(cl:ensure-generic-function 'roadQueries-val :lambda-list '(m))
(cl:defmethod roadQueries-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:roadQueries-val is deprecated.  Use RosAdapter-msg:roadQueries instead.")
  (roadQueries m))

(cl:ensure-generic-function 'egoStates-val :lambda-list '(m))
(cl:defmethod egoStates-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:egoStates-val is deprecated.  Use RosAdapter-msg:egoStates instead.")
  (egoStates m))

(cl:ensure-generic-function 'milObjStates-val :lambda-list '(m))
(cl:defmethod milObjStates-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:milObjStates-val is deprecated.  Use RosAdapter-msg:milObjStates instead.")
  (milObjStates m))

(cl:ensure-generic-function 'milRoadMarks-val :lambda-list '(m))
(cl:defmethod milRoadMarks-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:milRoadMarks-val is deprecated.  Use RosAdapter-msg:milRoadMarks instead.")
  (milRoadMarks m))

(cl:ensure-generic-function 'initParams-val :lambda-list '(m))
(cl:defmethod initParams-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:initParams-val is deprecated.  Use RosAdapter-msg:initParams instead.")
  (initParams m))

(cl:ensure-generic-function 'milAmesimSignals-val :lambda-list '(m))
(cl:defmethod milAmesimSignals-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:milAmesimSignals-val is deprecated.  Use RosAdapter-msg:milAmesimSignals instead.")
  (milAmesimSignals m))

(cl:ensure-generic-function 'activateControllers-val :lambda-list '(m))
(cl:defmethod activateControllers-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:activateControllers-val is deprecated.  Use RosAdapter-msg:activateControllers instead.")
  (activateControllers m))

(cl:ensure-generic-function 'assignControllers-val :lambda-list '(m))
(cl:defmethod assignControllers-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:assignControllers-val is deprecated.  Use RosAdapter-msg:assignControllers instead.")
  (assignControllers m))

(cl:ensure-generic-function 'overrideControllers-val :lambda-list '(m))
(cl:defmethod overrideControllers-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:overrideControllers-val is deprecated.  Use RosAdapter-msg:overrideControllers instead.")
  (overrideControllers m))

(cl:ensure-generic-function 'customCommands-val :lambda-list '(m))
(cl:defmethod customCommands-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:customCommands-val is deprecated.  Use RosAdapter-msg:customCommands instead.")
  (customCommands m))

(cl:ensure-generic-function 'parkingSpaces-val :lambda-list '(m))
(cl:defmethod parkingSpaces-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:parkingSpaces-val is deprecated.  Use RosAdapter-msg:parkingSpaces instead.")
  (parkingSpaces m))

(cl:ensure-generic-function 'driverCtrls-val :lambda-list '(m))
(cl:defmethod driverCtrls-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:driverCtrls-val is deprecated.  Use RosAdapter-msg:driverCtrls instead.")
  (driverCtrls m))

(cl:ensure-generic-function 'syncs-val :lambda-list '(m))
(cl:defmethod syncs-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:syncs-val is deprecated.  Use RosAdapter-msg:syncs instead.")
  (syncs m))

(cl:ensure-generic-function 'imuDatas-val :lambda-list '(m))
(cl:defmethod imuDatas-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:imuDatas-val is deprecated.  Use RosAdapter-msg:imuDatas instead.")
  (imuDatas m))

(cl:ensure-generic-function 'gnssGgaS-val :lambda-list '(m))
(cl:defmethod gnssGgaS-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:gnssGgaS-val is deprecated.  Use RosAdapter-msg:gnssGgaS instead.")
  (gnssGgaS m))

(cl:ensure-generic-function 'uwbDatas-val :lambda-list '(m))
(cl:defmethod uwbDatas-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:uwbDatas-val is deprecated.  Use RosAdapter-msg:uwbDatas instead.")
  (uwbDatas m))

(cl:ensure-generic-function 'modelOutlines-val :lambda-list '(m))
(cl:defmethod modelOutlines-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:modelOutlines-val is deprecated.  Use RosAdapter-msg:modelOutlines instead.")
  (modelOutlines m))

(cl:ensure-generic-function 'rsuVnfpInfo-val :lambda-list '(m))
(cl:defmethod rsuVnfpInfo-val ((m <rosSimproToAD>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader RosAdapter-msg:rsuVnfpInfo-val is deprecated.  Use RosAdapter-msg:rsuVnfpInfo instead.")
  (rsuVnfpInfo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <rosSimproToAD>) ostream)
  "Serializes a message object of type '<rosSimproToAD>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'head) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'laneInfos))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'laneInfos))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sensorStates))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'sensorStates))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sensorObjects))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'sensorObjects))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'contactPoints))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'contactPoints))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'trafficSigns))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'trafficSigns))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'roadStates))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'roadStates))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'environments))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'environments))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'trafficLights))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'trafficLights))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'roadQueries))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'roadQueries))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'egoStates))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'egoStates))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'milObjStates))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'milObjStates))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'milRoadMarks))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'milRoadMarks))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'initParams))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'initParams))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'milAmesimSignals))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'milAmesimSignals))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'activateControllers))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'activateControllers))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'assignControllers))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'assignControllers))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'overrideControllers))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'overrideControllers))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'customCommands))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'customCommands))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'parkingSpaces))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'parkingSpaces))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'driverCtrls))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'driverCtrls))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'syncs))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'syncs))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'imuDatas))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'imuDatas))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'gnssGgaS))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'gnssGgaS))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'uwbDatas))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'uwbDatas))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'modelOutlines))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'modelOutlines))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'rsuVnfpInfo) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <rosSimproToAD>) istream)
  "Deserializes a message object of type '<rosSimproToAD>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'head) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'laneInfos) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'laneInfos)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:lane_info))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sensorStates) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sensorStates)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:sensor_info))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sensorObjects) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sensorObjects)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:sensor_detection_info))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'contactPoints) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'contactPoints)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:contact_point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'trafficSigns) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'trafficSigns)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:traffic_sign))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'roadStates) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'roadStates)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:road_state))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'environments) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'environments)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:environment))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'trafficLights) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'trafficLights)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:traffic_light))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'roadQueries) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'roadQueries)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:road_query))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'egoStates) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'egoStates)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:mil_ego_state))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'milObjStates) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'milObjStates)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:mil_object_state))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'milRoadMarks) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'milRoadMarks)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:mil_roadmark))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'initParams) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'initParams)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:init_param))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'milAmesimSignals) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'milAmesimSignals)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:mil_amesim_signal))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'activateControllers) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'activateControllers)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:activate_controller))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'assignControllers) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'assignControllers)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:assign_controller))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'overrideControllers) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'overrideControllers)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:override_controller))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'customCommands) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'customCommands)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:custom_command))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'parkingSpaces) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'parkingSpaces)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:parkingSpace))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'driverCtrls) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'driverCtrls)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:driver_ctrl))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'syncs) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'syncs)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:sync))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'imuDatas) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'imuDatas)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:imu_data))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'gnssGgaS) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'gnssGgaS)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:gnss_gga))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'uwbDatas) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'uwbDatas)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:uwb_data))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'modelOutlines) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'modelOutlines)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'RosAdapter-msg:model_outline))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'rsuVnfpInfo) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<rosSimproToAD>)))
  "Returns string type for a message object of type '<rosSimproToAD>"
  "RosAdapter/rosSimproToAD")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'rosSimproToAD)))
  "Returns string type for a message object of type 'rosSimproToAD"
  "RosAdapter/rosSimproToAD")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<rosSimproToAD>)))
  "Returns md5sum for a message object of type '<rosSimproToAD>"
  "c51422c0a9306e26c68900e995989ad4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'rosSimproToAD)))
  "Returns md5sum for a message object of type 'rosSimproToAD"
  "c51422c0a9306e26c68900e995989ad4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<rosSimproToAD>)))
  "Returns full string definition for message of type '<rosSimproToAD>"
  (cl:format cl:nil "# simpro发送给AD的数据~%header                         head~%lane_info[]                    laneInfos~%sensor_info[]                  sensorStates~%sensor_detection_info[]        sensorObjects~%contact_point[]                contactPoints~%traffic_sign[]                 trafficSigns~%road_state[]                   roadStates~%environment[]                  environments~%traffic_light[]                trafficLights~%road_query[]                   roadQueries~%mil_ego_state[]                egoStates~%mil_object_state[]             milObjStates~%mil_roadmark[]                 milRoadMarks~%init_param[]                   initParams~%mil_amesim_signal[]            milAmesimSignals~%activate_controller[]          activateControllers~%assign_controller[]            assignControllers~%override_controller[]          overrideControllers~%custom_command[]               customCommands~%parkingSpace[]                 parkingSpaces~%driver_ctrl[]                  driverCtrls~%sync[]                         syncs   ~%imu_data[]                     imuDatas     ~%gnss_gga[]                     gnssGgaS~%uwb_data[]                     uwbDatas~%model_outline[]                modelOutlines~%rsu_vnfp_info                  rsuVnfpInfo~%================================================================================~%MSG: RosAdapter/header~%# /** ------ Msg header ------ */~%float64 u8SimTime~%uint32  u4HeaderSize~%uint32  u4DataSize~%uint32  u4FrameNo~%================================================================================~%MSG: RosAdapter/lane_info~%# /** ------ 车道信息 ------ */~%uint64   u8RoadId~%uint32   u4ObjectId~%float32  u4Width~%uint16   u2Type~%int8     u1Id~%uint8    u1NeighborMask~%int8     u1LeftLaneId~%int8     u1RightLaneId~%================================================================================~%MSG: RosAdapter/sensor_info~%# /** ------ 传感器定义和状态 ------ */~%coord      sPos~%coord      sOriginCoordSys~%string     au1Name~%uint32     u8HostId~%uint32     u8Id~%float32[]  au4FovHV~%float32[]  au4ClipNF~%float32[]  au4FovOffHV~%uint8      u1Type                   ~%uint8      u1ModelType~%float64	   u4IdealFreq~%uint32	   u4ResL~%uint32     u4ResV~%float64	   u4SenSizeL~%float64	   u4SenSizeW~%float64	   u4LenFd~%float64	   u4DistCenL~%float64	   u4DistCenW~%float64	   u4DistParK1~%float64	   u4DistParK2~%~%================================================================================~%MSG: RosAdapter/coord~%# /** ------ 坐标 ------ */~%float64   u8X~%float64   u8Y~%float64   u8Z~%float32   u4H~%float32   u4P~%float32   u4R~%uint8     u1Type~%================================================================================~%MSG: RosAdapter/sensor_detection_info~%# 传感器监测物体所有信息~%~%uint32            u4Id~%uint32            u4SensorId~%uint16            u2Flags~%uint8             u1Type~%int8              u1Occlusion~%int8              u1DeltaLanePos~%uint8             u1ValidFlag~%float64           u8ExistProb~%float64           u8TypeIdProb~%object_uion       sExtraInfo~%================================================================================~%MSG: RosAdapter/object_uion~%dynamic_object sDynamicObj~%mark_object    sMarkObj~%sign_object    sSignObj ~%================================================================================~%MSG: RosAdapter/dynamic_object~%# /** ------ 传感器探测到的对象信息 ------ */~%~%float64    u8Dist~%float64    u8NearestDist~%float64    u8RelativeVelx~%float64    u8RelativeVely~%float64    u8RelativeAccx~%float64    u8RelativeAccy~%float64    u8HeadingAngle~%coord      sSensorPos~%coord      sNearestSensorPos~%coord      sSenNearestPosXL~%coord      sSenNearestPosXR~%coord      sSenNearestPosYL~%coord      sSenNearestPosYR~%point3d[]  sBoundingBox~%uint8      u1MovingSt~%================================================================================~%MSG: RosAdapter/point3d~%float64      u8x~%float64      u8y~%float64      u8z~%================================================================================~%MSG: RosAdapter/mark_object~%# 车道线~%~%float64[]	 au8RoadMarkCoeffL~%float64[]	 au8RoadMarkCoeffR~%================================================================================~%MSG: RosAdapter/sign_object~%# 交通标志~%~%float64   u8Dist~%float64   u8NearestDist~%float64   u8TrafficSignDistX~%float64   u8TrafficSignDistY~%coord     sSensorPos~%coord     sNearestSensorPos~%uint8     u1TrafficSignType~%================================================================================~%MSG: RosAdapter/contact_point~%# /** ------ 接触点信息 ------ */~%coord  sRoadDataIn~%uint16 u2Id~%================================================================================~%MSG: RosAdapter/traffic_sign~%# /** ------ 交通标志信息 ------ */~%string  au1Type~%coord   sPos~%uint32  u4TrafficSignId~%uint32  u4ObjectId~%string  au1SubType~%float32 u4RoadDist~%float32 u4Value~%int8    u1MinLane~%int8    u1MaxLane~%================================================================================~%MSG: RosAdapter/road_state~%#/** ------ 车辆对应的道路状态 ------ */~%uint64  u8RoadId~%uint32  u4ObjectId~%float32 u4DefaultSpeed~%float32 u4WaterLevel~%float32 u4DistToJunc~%================================================================================~%MSG: RosAdapter/environment~%# /** ------ 环境信息 ------ */~%float64      u8RainIntensity~%float64      u8SnowIntensity~%float64      u8FogIntensity~%float64      u8FogVisualRange~%uint32       u4TimeOfDay~%int16        u2TimeZoneMinutesWest~%uint16       u2Year~%uint8        u1CloudState~%uint8        u1Day~%uint8        u1Month~%================================================================================~%MSG: RosAdapter/traffic_light~%# /** ------ 交通灯信息 ------ */~%int32                    u4Id~%int32                    u4CtrlId~%uint32                   u4NoPhases~%uint32                   u4DataSize~%float32                  u4State~%float32                  u4CycleTime~%traffic_light_phase[]    phases~%================================================================================~%MSG: RosAdapter/traffic_light_phase~%# /** ------ 交通灯相位信息 ------ */~%~%float32     u4Duration~%uint8       u1Status   ~%================================================================================~%MSG: RosAdapter/road_query~%# /** ------ 查询道路点 ------ */~%float32 u8X~%float32 u8Y~%uint16  u2Id~%================================================================================~%MSG: RosAdapter/mil_ego_state~%# /** ------ MIL测试主车信息描述包 ------ */~%~%object_state   sObjectState~%float64        u4initSpeed~%float64        u8DistRoadEnd~%uint32         u4LightMask               ~%float32        u4WheelSpeedFL~%float32        u4WheelSpeedFR~%float32        u4WheelSpeedRL~%float32        u4WheelSpeedRR~%float32        u4MasterCylinderPressure~%float32        u4WheelHeightLF~%float32        u4WheelHeightLR~%float32        u4WheelHeightRF~%float32        u4WheelHeightRR~%float32        u4SteerAngle~%uint8          u1objQuantity~%uint8          u1irc_id~%uint8          u1irc_left_id~%uint8          u1irc_right_id~%uint8          u1cipv_id~%uint8          u1lmc_id~%uint8          u1rmc_id~%uint8          u1isReachInitSpeed~%================================================================================~%MSG: RosAdapter/object_state~%# /** ------ 对象信息 ------ */~%coord           sSpeed~%coord           sAccel~%geometry        sGeo~%coord           sPos~%string          au1Name~%string          au1ModelFileName~%string          au1ModelName~%float64[]       au8ParamScale~%uint64          u8RoadId~%float64         u8SpeedLimit~%uint32          u4Id~%float32         u4RoadS~%float32         u4RoadT~%float32         u4HdgRel~%float32         u4LaneOffset~%float32         u4TraveledDist~%uint16          u2visMask~%uint8           u1Type~%int8            u1LaneId~%uint8           u1Dir~%bool            u1IsOnRoad~%uint8           u1category~%================================================================================~%MSG: RosAdapter/geometry~%# /** ------ 几何信息 ------ */~%float32 u4DimX~%float32 u4DimY~%float32 u4DimZ~%float32 u4OffX~%float32 u4OffY~%float32 u4OffZ~%================================================================================~%MSG: RosAdapter/mil_object_state~%# /** ------ MIL测试环境车、行人、障碍物信息 ------ */~%object_state           sObjectState~%mil_object_state_base  sMilBase~%================================================================================~%MSG: RosAdapter/mil_object_state_base~%#/** ------ MIL测试环境车、行人、障碍物信息描述包 ------ */~%~%uint32     u4LightMask~%float32    u4DistanceX~%float32    u4DistanceY~%float32    u4VelocityX~%float32    u4VelocityY~%float32    u4AccelerationX~%float32    u4AccelerationY~%float32    u4YawRate~%float32    u4Dist~%float32    u4Angle~%uint8      u1ObjClass~%uint8      u1Flag_detected~%uint8      u1Movable~%uint8      u1Moving~%uint8      u1Obj_Age~%================================================================================~%MSG: RosAdapter/mil_roadmark~% # /** ------ MIL测试车道线信息描述包 ------ */~%~%uint64  u8RoadId~%float64 curvVert~%float32 u4StartDx~%float32 u4Width~%float32 u4ViewRangeStart~%float32 u4ViewRangeEnd~%float32 u4MeasuredVREnd~%float32 u4C0~%float32 u4C1~%float32 u4C2~%float32 u4C3~%uint16  u2LaneChange~%int8    u1LaneId~%uint8   u1Quality~%uint8   u1Type~%uint8   u1Color~%uint8   u1LeftCrossing~%uint8   u1RightCrossing~%================================================================================~%MSG: RosAdapter/init_param~%# /** ------ 初始化参数 ------ */~%~%string             au1OpenScenario~%string             au1OpenDrive~%uint64             u8StartRoadId~%uint64             u8EndRoadId~%float32            u4StartRoadS~%float32            u4EndRoadS~%float32            u4Speed~%uint16             u2ScenarioId~%int8               u1StartLaneId~%int8               u1EndLaneId~%================================================================================~%MSG: RosAdapter/mil_amesim_signal~%# /** ------ MIL AMESim 测试信息描述包 ------ */~%~%float32       u4LeftLen~%float32       u4NextLen~%float32       u4NextAgeSpeed~%float32       u4NextMinSpeed~%float32       u4NextMaxSpeed~%float32       u4NextGradient~%float32       u4NextCongest~%uint8         u1RoadType~%float32       u4DisLimit~%bool          u1IsFarAwayLimit~%float32       u4LimitSpeed~%bool          ulIsJunction~%float32       u4DisJunction~%bool          ulIsFarAwayJunc~%uint8         ultrafficLightStat~%float32       u4Curvity~%float32       u4RelativeVel~%float32       u4RelativeDis~%================================================================================~%MSG: RosAdapter/activate_controller~%# /** ------激活控制器 ------ */~%~%uint32          u4ObjectId~%bool            u1Lateral~%bool            u1Longitudinal~%================================================================================~%MSG: RosAdapter/assign_controller~%# /** ------分配控制器 ------ */~%~%string                               au1ControllerName~%uint32                               u4ObjectId~%uint32                               u4PropertyNum~%assign_controller_property[]         properties~%================================================================================~%MSG: RosAdapter/assign_controller_property~%# /** ------分配控制器的属性信息 ------ */~%~%string   au1Name~%string   au1Value~%================================================================================~%MSG: RosAdapter/override_controller~%# /** ------接管控制器 ------ */~%~%float64   u8ThrottleValue~%float64   u8BrakeValue~%float64   u8SteeringWheelValue~%float64   u8ParkingBrakeValue~%float64   u8ClutchValue~%float64   u8GearValue~%uint32    u4ObjectId~%bool      u1ThrottleActive~%bool      u1BrakeActive~%bool      u1SteeringWheelActive~%bool      u1ParkingBrakeActive~%bool      u1ClutchActive~%bool      u1GearActive~%================================================================================~%MSG: RosAdapter/custom_command~%# /** ------自定义指令 ------ */~%~%string   au1Type~%string   au1Command~%uint32   u4ObjectId~%================================================================================~%MSG: RosAdapter/parkingSpace~%#/** ------ 停车位信息 ------ */~%geometry  sGeo~%coord     sPos~%float32   u4RoadS~%float32   u4RoadT~%uint64    u8SlotId~%~%================================================================================~%MSG: RosAdapter/driver_ctrl~%# /** ------ 驾驶员控制输入的信息 ------ */~%~%uint32       u4ObjectId~%float32      u4MtWheel~%float64      u8MasterCylinderPressure~%float64      u8SteeringWheel~%float64      u8ThrottlePedal~%float64      u8BrakePedal~%float64      u8AccelTgt~%float64      u8SteeringTorque~%float64      u8StopDistance~%float64      u8TargetSpeed~%float64      u8Vx~%float64      u8Wr~%float64      u8VLFWheelSpd~%float64      u8VRFWheelSpd~%float64      u8VLRWheelSpd~%float64      u8VRRWheelSpd~%float64      u8Ax~%float64      u8Ay~%float64      u8SteeringWheelAngularRate~%float64      u8DrvTorqAct~%float64      u8Xmc~%float64      u8Ymc~%float64      u8YawThetaVehicle~%float64      u8PitchThetaVehicle~%float64      u8RollThetaVehicle~%float64      u8PitchRateVehicle~%float64      u8RollRateVehicle~%float64      u8SinSlopeout~%float64      u8VehicleCurv~%float64      u8TmotorCmd~%float64      u8Tmotor~%float64      u8EnergySourceLevel~%float64      u8WLFWheelSpd~%float64      u8WRFWheelSpd~%float64      u8WLRWheelSpd~%float64      u8WRRWheelSpd~%float64      u8WGearSpd~%uint8        u1LFWheelRotatedDir~%uint8        u1LRWheelRotatedDir~%uint8        u1RFWheelRotatedDir~%uint8        u1RRWheelRotatedDir~%uint8        u1BrakePedalStatus~%uint8        u1VehicleDir~%uint8        u1BrkType~%int8         u1Gear ~%================================================================================~%MSG: RosAdapter/sync~%# /** ------ 同步信号 ------ */~%uint32 u4CmdMask~%uint32 u4UserData~%================================================================================~%MSG: RosAdapter/imu_data~%uint8         msgcnt~%float64       u8X~%float64       u8Y~%float64       u8Z~%float64       yaw~%float64       pitch~%float64       roll~%================================================================================~%MSG: RosAdapter/gnss_gga~%uint8         startChar~%uint8[]       cmd~%uint8[]       mTime~%float64       lat~%uint8         NorS~%float64       lon~%uint8         EorW~%uint8[]       mode~%int32         count~%float64       horizonprecious ~%float64       geoidalheight~%uint8         meter1~%float64       height~%uint8         meter2~%float64       dataage~%int32         basestationflag~%uint8         sperator~%uint8[]       checksum~%================================================================================~%MSG: RosAdapter/uwb_data~%uint8         msgcnt~%float64       u8x~%float64       u8y~%float64       u8z~%================================================================================~%MSG: RosAdapter/model_outline~%string                au1ModelName~%double_array[]        au8OutlinePoints    ~%================================================================================~%MSG: RosAdapter/double_array~%float64[]  data~%================================================================================~%MSG: RosAdapter/rsu_vnfp_info~%uint32    type~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'rosSimproToAD)))
  "Returns full string definition for message of type 'rosSimproToAD"
  (cl:format cl:nil "# simpro发送给AD的数据~%header                         head~%lane_info[]                    laneInfos~%sensor_info[]                  sensorStates~%sensor_detection_info[]        sensorObjects~%contact_point[]                contactPoints~%traffic_sign[]                 trafficSigns~%road_state[]                   roadStates~%environment[]                  environments~%traffic_light[]                trafficLights~%road_query[]                   roadQueries~%mil_ego_state[]                egoStates~%mil_object_state[]             milObjStates~%mil_roadmark[]                 milRoadMarks~%init_param[]                   initParams~%mil_amesim_signal[]            milAmesimSignals~%activate_controller[]          activateControllers~%assign_controller[]            assignControllers~%override_controller[]          overrideControllers~%custom_command[]               customCommands~%parkingSpace[]                 parkingSpaces~%driver_ctrl[]                  driverCtrls~%sync[]                         syncs   ~%imu_data[]                     imuDatas     ~%gnss_gga[]                     gnssGgaS~%uwb_data[]                     uwbDatas~%model_outline[]                modelOutlines~%rsu_vnfp_info                  rsuVnfpInfo~%================================================================================~%MSG: RosAdapter/header~%# /** ------ Msg header ------ */~%float64 u8SimTime~%uint32  u4HeaderSize~%uint32  u4DataSize~%uint32  u4FrameNo~%================================================================================~%MSG: RosAdapter/lane_info~%# /** ------ 车道信息 ------ */~%uint64   u8RoadId~%uint32   u4ObjectId~%float32  u4Width~%uint16   u2Type~%int8     u1Id~%uint8    u1NeighborMask~%int8     u1LeftLaneId~%int8     u1RightLaneId~%================================================================================~%MSG: RosAdapter/sensor_info~%# /** ------ 传感器定义和状态 ------ */~%coord      sPos~%coord      sOriginCoordSys~%string     au1Name~%uint32     u8HostId~%uint32     u8Id~%float32[]  au4FovHV~%float32[]  au4ClipNF~%float32[]  au4FovOffHV~%uint8      u1Type                   ~%uint8      u1ModelType~%float64	   u4IdealFreq~%uint32	   u4ResL~%uint32     u4ResV~%float64	   u4SenSizeL~%float64	   u4SenSizeW~%float64	   u4LenFd~%float64	   u4DistCenL~%float64	   u4DistCenW~%float64	   u4DistParK1~%float64	   u4DistParK2~%~%================================================================================~%MSG: RosAdapter/coord~%# /** ------ 坐标 ------ */~%float64   u8X~%float64   u8Y~%float64   u8Z~%float32   u4H~%float32   u4P~%float32   u4R~%uint8     u1Type~%================================================================================~%MSG: RosAdapter/sensor_detection_info~%# 传感器监测物体所有信息~%~%uint32            u4Id~%uint32            u4SensorId~%uint16            u2Flags~%uint8             u1Type~%int8              u1Occlusion~%int8              u1DeltaLanePos~%uint8             u1ValidFlag~%float64           u8ExistProb~%float64           u8TypeIdProb~%object_uion       sExtraInfo~%================================================================================~%MSG: RosAdapter/object_uion~%dynamic_object sDynamicObj~%mark_object    sMarkObj~%sign_object    sSignObj ~%================================================================================~%MSG: RosAdapter/dynamic_object~%# /** ------ 传感器探测到的对象信息 ------ */~%~%float64    u8Dist~%float64    u8NearestDist~%float64    u8RelativeVelx~%float64    u8RelativeVely~%float64    u8RelativeAccx~%float64    u8RelativeAccy~%float64    u8HeadingAngle~%coord      sSensorPos~%coord      sNearestSensorPos~%coord      sSenNearestPosXL~%coord      sSenNearestPosXR~%coord      sSenNearestPosYL~%coord      sSenNearestPosYR~%point3d[]  sBoundingBox~%uint8      u1MovingSt~%================================================================================~%MSG: RosAdapter/point3d~%float64      u8x~%float64      u8y~%float64      u8z~%================================================================================~%MSG: RosAdapter/mark_object~%# 车道线~%~%float64[]	 au8RoadMarkCoeffL~%float64[]	 au8RoadMarkCoeffR~%================================================================================~%MSG: RosAdapter/sign_object~%# 交通标志~%~%float64   u8Dist~%float64   u8NearestDist~%float64   u8TrafficSignDistX~%float64   u8TrafficSignDistY~%coord     sSensorPos~%coord     sNearestSensorPos~%uint8     u1TrafficSignType~%================================================================================~%MSG: RosAdapter/contact_point~%# /** ------ 接触点信息 ------ */~%coord  sRoadDataIn~%uint16 u2Id~%================================================================================~%MSG: RosAdapter/traffic_sign~%# /** ------ 交通标志信息 ------ */~%string  au1Type~%coord   sPos~%uint32  u4TrafficSignId~%uint32  u4ObjectId~%string  au1SubType~%float32 u4RoadDist~%float32 u4Value~%int8    u1MinLane~%int8    u1MaxLane~%================================================================================~%MSG: RosAdapter/road_state~%#/** ------ 车辆对应的道路状态 ------ */~%uint64  u8RoadId~%uint32  u4ObjectId~%float32 u4DefaultSpeed~%float32 u4WaterLevel~%float32 u4DistToJunc~%================================================================================~%MSG: RosAdapter/environment~%# /** ------ 环境信息 ------ */~%float64      u8RainIntensity~%float64      u8SnowIntensity~%float64      u8FogIntensity~%float64      u8FogVisualRange~%uint32       u4TimeOfDay~%int16        u2TimeZoneMinutesWest~%uint16       u2Year~%uint8        u1CloudState~%uint8        u1Day~%uint8        u1Month~%================================================================================~%MSG: RosAdapter/traffic_light~%# /** ------ 交通灯信息 ------ */~%int32                    u4Id~%int32                    u4CtrlId~%uint32                   u4NoPhases~%uint32                   u4DataSize~%float32                  u4State~%float32                  u4CycleTime~%traffic_light_phase[]    phases~%================================================================================~%MSG: RosAdapter/traffic_light_phase~%# /** ------ 交通灯相位信息 ------ */~%~%float32     u4Duration~%uint8       u1Status   ~%================================================================================~%MSG: RosAdapter/road_query~%# /** ------ 查询道路点 ------ */~%float32 u8X~%float32 u8Y~%uint16  u2Id~%================================================================================~%MSG: RosAdapter/mil_ego_state~%# /** ------ MIL测试主车信息描述包 ------ */~%~%object_state   sObjectState~%float64        u4initSpeed~%float64        u8DistRoadEnd~%uint32         u4LightMask               ~%float32        u4WheelSpeedFL~%float32        u4WheelSpeedFR~%float32        u4WheelSpeedRL~%float32        u4WheelSpeedRR~%float32        u4MasterCylinderPressure~%float32        u4WheelHeightLF~%float32        u4WheelHeightLR~%float32        u4WheelHeightRF~%float32        u4WheelHeightRR~%float32        u4SteerAngle~%uint8          u1objQuantity~%uint8          u1irc_id~%uint8          u1irc_left_id~%uint8          u1irc_right_id~%uint8          u1cipv_id~%uint8          u1lmc_id~%uint8          u1rmc_id~%uint8          u1isReachInitSpeed~%================================================================================~%MSG: RosAdapter/object_state~%# /** ------ 对象信息 ------ */~%coord           sSpeed~%coord           sAccel~%geometry        sGeo~%coord           sPos~%string          au1Name~%string          au1ModelFileName~%string          au1ModelName~%float64[]       au8ParamScale~%uint64          u8RoadId~%float64         u8SpeedLimit~%uint32          u4Id~%float32         u4RoadS~%float32         u4RoadT~%float32         u4HdgRel~%float32         u4LaneOffset~%float32         u4TraveledDist~%uint16          u2visMask~%uint8           u1Type~%int8            u1LaneId~%uint8           u1Dir~%bool            u1IsOnRoad~%uint8           u1category~%================================================================================~%MSG: RosAdapter/geometry~%# /** ------ 几何信息 ------ */~%float32 u4DimX~%float32 u4DimY~%float32 u4DimZ~%float32 u4OffX~%float32 u4OffY~%float32 u4OffZ~%================================================================================~%MSG: RosAdapter/mil_object_state~%# /** ------ MIL测试环境车、行人、障碍物信息 ------ */~%object_state           sObjectState~%mil_object_state_base  sMilBase~%================================================================================~%MSG: RosAdapter/mil_object_state_base~%#/** ------ MIL测试环境车、行人、障碍物信息描述包 ------ */~%~%uint32     u4LightMask~%float32    u4DistanceX~%float32    u4DistanceY~%float32    u4VelocityX~%float32    u4VelocityY~%float32    u4AccelerationX~%float32    u4AccelerationY~%float32    u4YawRate~%float32    u4Dist~%float32    u4Angle~%uint8      u1ObjClass~%uint8      u1Flag_detected~%uint8      u1Movable~%uint8      u1Moving~%uint8      u1Obj_Age~%================================================================================~%MSG: RosAdapter/mil_roadmark~% # /** ------ MIL测试车道线信息描述包 ------ */~%~%uint64  u8RoadId~%float64 curvVert~%float32 u4StartDx~%float32 u4Width~%float32 u4ViewRangeStart~%float32 u4ViewRangeEnd~%float32 u4MeasuredVREnd~%float32 u4C0~%float32 u4C1~%float32 u4C2~%float32 u4C3~%uint16  u2LaneChange~%int8    u1LaneId~%uint8   u1Quality~%uint8   u1Type~%uint8   u1Color~%uint8   u1LeftCrossing~%uint8   u1RightCrossing~%================================================================================~%MSG: RosAdapter/init_param~%# /** ------ 初始化参数 ------ */~%~%string             au1OpenScenario~%string             au1OpenDrive~%uint64             u8StartRoadId~%uint64             u8EndRoadId~%float32            u4StartRoadS~%float32            u4EndRoadS~%float32            u4Speed~%uint16             u2ScenarioId~%int8               u1StartLaneId~%int8               u1EndLaneId~%================================================================================~%MSG: RosAdapter/mil_amesim_signal~%# /** ------ MIL AMESim 测试信息描述包 ------ */~%~%float32       u4LeftLen~%float32       u4NextLen~%float32       u4NextAgeSpeed~%float32       u4NextMinSpeed~%float32       u4NextMaxSpeed~%float32       u4NextGradient~%float32       u4NextCongest~%uint8         u1RoadType~%float32       u4DisLimit~%bool          u1IsFarAwayLimit~%float32       u4LimitSpeed~%bool          ulIsJunction~%float32       u4DisJunction~%bool          ulIsFarAwayJunc~%uint8         ultrafficLightStat~%float32       u4Curvity~%float32       u4RelativeVel~%float32       u4RelativeDis~%================================================================================~%MSG: RosAdapter/activate_controller~%# /** ------激活控制器 ------ */~%~%uint32          u4ObjectId~%bool            u1Lateral~%bool            u1Longitudinal~%================================================================================~%MSG: RosAdapter/assign_controller~%# /** ------分配控制器 ------ */~%~%string                               au1ControllerName~%uint32                               u4ObjectId~%uint32                               u4PropertyNum~%assign_controller_property[]         properties~%================================================================================~%MSG: RosAdapter/assign_controller_property~%# /** ------分配控制器的属性信息 ------ */~%~%string   au1Name~%string   au1Value~%================================================================================~%MSG: RosAdapter/override_controller~%# /** ------接管控制器 ------ */~%~%float64   u8ThrottleValue~%float64   u8BrakeValue~%float64   u8SteeringWheelValue~%float64   u8ParkingBrakeValue~%float64   u8ClutchValue~%float64   u8GearValue~%uint32    u4ObjectId~%bool      u1ThrottleActive~%bool      u1BrakeActive~%bool      u1SteeringWheelActive~%bool      u1ParkingBrakeActive~%bool      u1ClutchActive~%bool      u1GearActive~%================================================================================~%MSG: RosAdapter/custom_command~%# /** ------自定义指令 ------ */~%~%string   au1Type~%string   au1Command~%uint32   u4ObjectId~%================================================================================~%MSG: RosAdapter/parkingSpace~%#/** ------ 停车位信息 ------ */~%geometry  sGeo~%coord     sPos~%float32   u4RoadS~%float32   u4RoadT~%uint64    u8SlotId~%~%================================================================================~%MSG: RosAdapter/driver_ctrl~%# /** ------ 驾驶员控制输入的信息 ------ */~%~%uint32       u4ObjectId~%float32      u4MtWheel~%float64      u8MasterCylinderPressure~%float64      u8SteeringWheel~%float64      u8ThrottlePedal~%float64      u8BrakePedal~%float64      u8AccelTgt~%float64      u8SteeringTorque~%float64      u8StopDistance~%float64      u8TargetSpeed~%float64      u8Vx~%float64      u8Wr~%float64      u8VLFWheelSpd~%float64      u8VRFWheelSpd~%float64      u8VLRWheelSpd~%float64      u8VRRWheelSpd~%float64      u8Ax~%float64      u8Ay~%float64      u8SteeringWheelAngularRate~%float64      u8DrvTorqAct~%float64      u8Xmc~%float64      u8Ymc~%float64      u8YawThetaVehicle~%float64      u8PitchThetaVehicle~%float64      u8RollThetaVehicle~%float64      u8PitchRateVehicle~%float64      u8RollRateVehicle~%float64      u8SinSlopeout~%float64      u8VehicleCurv~%float64      u8TmotorCmd~%float64      u8Tmotor~%float64      u8EnergySourceLevel~%float64      u8WLFWheelSpd~%float64      u8WRFWheelSpd~%float64      u8WLRWheelSpd~%float64      u8WRRWheelSpd~%float64      u8WGearSpd~%uint8        u1LFWheelRotatedDir~%uint8        u1LRWheelRotatedDir~%uint8        u1RFWheelRotatedDir~%uint8        u1RRWheelRotatedDir~%uint8        u1BrakePedalStatus~%uint8        u1VehicleDir~%uint8        u1BrkType~%int8         u1Gear ~%================================================================================~%MSG: RosAdapter/sync~%# /** ------ 同步信号 ------ */~%uint32 u4CmdMask~%uint32 u4UserData~%================================================================================~%MSG: RosAdapter/imu_data~%uint8         msgcnt~%float64       u8X~%float64       u8Y~%float64       u8Z~%float64       yaw~%float64       pitch~%float64       roll~%================================================================================~%MSG: RosAdapter/gnss_gga~%uint8         startChar~%uint8[]       cmd~%uint8[]       mTime~%float64       lat~%uint8         NorS~%float64       lon~%uint8         EorW~%uint8[]       mode~%int32         count~%float64       horizonprecious ~%float64       geoidalheight~%uint8         meter1~%float64       height~%uint8         meter2~%float64       dataage~%int32         basestationflag~%uint8         sperator~%uint8[]       checksum~%================================================================================~%MSG: RosAdapter/uwb_data~%uint8         msgcnt~%float64       u8x~%float64       u8y~%float64       u8z~%================================================================================~%MSG: RosAdapter/model_outline~%string                au1ModelName~%double_array[]        au8OutlinePoints    ~%================================================================================~%MSG: RosAdapter/double_array~%float64[]  data~%================================================================================~%MSG: RosAdapter/rsu_vnfp_info~%uint32    type~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <rosSimproToAD>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'head))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'laneInfos) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sensorStates) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sensorObjects) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'contactPoints) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'trafficSigns) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'roadStates) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'environments) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'trafficLights) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'roadQueries) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'egoStates) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'milObjStates) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'milRoadMarks) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'initParams) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'milAmesimSignals) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'activateControllers) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'assignControllers) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'overrideControllers) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'customCommands) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'parkingSpaces) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'driverCtrls) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'syncs) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'imuDatas) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'gnssGgaS) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'uwbDatas) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'modelOutlines) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'rsuVnfpInfo))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <rosSimproToAD>))
  "Converts a ROS message object to a list"
  (cl:list 'rosSimproToAD
    (cl:cons ':head (head msg))
    (cl:cons ':laneInfos (laneInfos msg))
    (cl:cons ':sensorStates (sensorStates msg))
    (cl:cons ':sensorObjects (sensorObjects msg))
    (cl:cons ':contactPoints (contactPoints msg))
    (cl:cons ':trafficSigns (trafficSigns msg))
    (cl:cons ':roadStates (roadStates msg))
    (cl:cons ':environments (environments msg))
    (cl:cons ':trafficLights (trafficLights msg))
    (cl:cons ':roadQueries (roadQueries msg))
    (cl:cons ':egoStates (egoStates msg))
    (cl:cons ':milObjStates (milObjStates msg))
    (cl:cons ':milRoadMarks (milRoadMarks msg))
    (cl:cons ':initParams (initParams msg))
    (cl:cons ':milAmesimSignals (milAmesimSignals msg))
    (cl:cons ':activateControllers (activateControllers msg))
    (cl:cons ':assignControllers (assignControllers msg))
    (cl:cons ':overrideControllers (overrideControllers msg))
    (cl:cons ':customCommands (customCommands msg))
    (cl:cons ':parkingSpaces (parkingSpaces msg))
    (cl:cons ':driverCtrls (driverCtrls msg))
    (cl:cons ':syncs (syncs msg))
    (cl:cons ':imuDatas (imuDatas msg))
    (cl:cons ':gnssGgaS (gnssGgaS msg))
    (cl:cons ':uwbDatas (uwbDatas msg))
    (cl:cons ':modelOutlines (modelOutlines msg))
    (cl:cons ':rsuVnfpInfo (rsuVnfpInfo msg))
))
