# /** ------ MIL AMESim 测试信息描述包 ------ */

float32       u4LeftLen
float32       u4NextLen
float32       u4NextAgeSpeed
float32       u4NextMinSpeed
float32       u4NextMaxSpeed
float32       u4NextGradient
float32       u4NextCongest
uint8         u1RoadType
float32       u4DisLimit
bool          u1IsFarAwayLimit
float32       u4LimitSpeed
bool          ulIsJunction
float32       u4DisJunction
bool          ulIsFarAwayJunc
uint8         ultrafficLightStat
float32       u4Curvity
float32       u4RelativeVel
float32       u4RelativeDis