// Generated by gencpp from file RosAdapter/traffic_light_phase.msg
// DO NOT EDIT!


#ifndef ROSADAPTER_MESSAGE_TRAFFIC_LIGHT_PHASE_H
#define ROSADAPTER_MESSAGE_TRAFFIC_LIGHT_PHASE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RosAdapter
{
template <class ContainerAllocator>
struct traffic_light_phase_
{
  typedef traffic_light_phase_<ContainerAllocator> Type;

  traffic_light_phase_()
    : u4Duration(0.0)
    , u1Status(0)  {
    }
  traffic_light_phase_(const ContainerAllocator& _alloc)
    : u4Duration(0.0)
    , u1Status(0)  {
  (void)_alloc;
    }



   typedef float _u4Duration_type;
  _u4Duration_type u4Duration;

   typedef uint8_t _u1Status_type;
  _u1Status_type u1Status;





  typedef boost::shared_ptr< ::RosAdapter::traffic_light_phase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RosAdapter::traffic_light_phase_<ContainerAllocator> const> ConstPtr;

}; // struct traffic_light_phase_

typedef ::RosAdapter::traffic_light_phase_<std::allocator<void> > traffic_light_phase;

typedef boost::shared_ptr< ::RosAdapter::traffic_light_phase > traffic_light_phasePtr;
typedef boost::shared_ptr< ::RosAdapter::traffic_light_phase const> traffic_light_phaseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RosAdapter::traffic_light_phase_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RosAdapter::traffic_light_phase_<ContainerAllocator1> & lhs, const ::RosAdapter::traffic_light_phase_<ContainerAllocator2> & rhs)
{
  return lhs.u4Duration == rhs.u4Duration &&
    lhs.u1Status == rhs.u1Status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RosAdapter::traffic_light_phase_<ContainerAllocator1> & lhs, const ::RosAdapter::traffic_light_phase_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RosAdapter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosAdapter::traffic_light_phase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RosAdapter::traffic_light_phase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosAdapter::traffic_light_phase_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1ac58ef8e89d4655dd7a1a78a5c64d9";
  }

  static const char* value(const ::RosAdapter::traffic_light_phase_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1ac58ef8e89d465ULL;
  static const uint64_t static_value2 = 0x5dd7a1a78a5c64d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RosAdapter/traffic_light_phase";
  }

  static const char* value(const ::RosAdapter::traffic_light_phase_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# /** ------ 交通灯相位信息 ------ */\n"
"\n"
"float32     u4Duration\n"
"uint8       u1Status   \n"
;
  }

  static const char* value(const ::RosAdapter::traffic_light_phase_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.u4Duration);
      stream.next(m.u1Status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traffic_light_phase_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RosAdapter::traffic_light_phase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RosAdapter::traffic_light_phase_<ContainerAllocator>& v)
  {
    s << indent << "u4Duration: ";
    Printer<float>::stream(s, indent + "  ", v.u4Duration);
    s << indent << "u1Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.u1Status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSADAPTER_MESSAGE_TRAFFIC_LIGHT_PHASE_H
