# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from RosAdapter/dynamic_object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import RosAdapter.msg

class dynamic_object(genpy.Message):
  _md5sum = "f0fca4830c1def89864a68dc2897f16f"
  _type = "RosAdapter/dynamic_object"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# /** ------ 传感器探测到的对象信息 ------ */

float64    u8Dist
float64    u8NearestDist
float64    u8RelativeVelx
float64    u8RelativeVely
float64    u8RelativeAccx
float64    u8RelativeAccy
float64    u8HeadingAngle
coord      sSensorPos
coord      sNearestSensorPos
coord      sSenNearestPosXL
coord      sSenNearestPosXR
coord      sSenNearestPosYL
coord      sSenNearestPosYR
point3d[]  sBoundingBox
uint8      u1MovingSt
================================================================================
MSG: RosAdapter/coord
# /** ------ 坐标 ------ */
float64   u8X
float64   u8Y
float64   u8Z
float32   u4H
float32   u4P
float32   u4R
uint8     u1Type
================================================================================
MSG: RosAdapter/point3d
float64      u8x
float64      u8y
float64      u8z"""
  __slots__ = ['u8Dist','u8NearestDist','u8RelativeVelx','u8RelativeVely','u8RelativeAccx','u8RelativeAccy','u8HeadingAngle','sSensorPos','sNearestSensorPos','sSenNearestPosXL','sSenNearestPosXR','sSenNearestPosYL','sSenNearestPosYR','sBoundingBox','u1MovingSt']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','RosAdapter/coord','RosAdapter/coord','RosAdapter/coord','RosAdapter/coord','RosAdapter/coord','RosAdapter/coord','RosAdapter/point3d[]','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       u8Dist,u8NearestDist,u8RelativeVelx,u8RelativeVely,u8RelativeAccx,u8RelativeAccy,u8HeadingAngle,sSensorPos,sNearestSensorPos,sSenNearestPosXL,sSenNearestPosXR,sSenNearestPosYL,sSenNearestPosYR,sBoundingBox,u1MovingSt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(dynamic_object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.u8Dist is None:
        self.u8Dist = 0.
      if self.u8NearestDist is None:
        self.u8NearestDist = 0.
      if self.u8RelativeVelx is None:
        self.u8RelativeVelx = 0.
      if self.u8RelativeVely is None:
        self.u8RelativeVely = 0.
      if self.u8RelativeAccx is None:
        self.u8RelativeAccx = 0.
      if self.u8RelativeAccy is None:
        self.u8RelativeAccy = 0.
      if self.u8HeadingAngle is None:
        self.u8HeadingAngle = 0.
      if self.sSensorPos is None:
        self.sSensorPos = RosAdapter.msg.coord()
      if self.sNearestSensorPos is None:
        self.sNearestSensorPos = RosAdapter.msg.coord()
      if self.sSenNearestPosXL is None:
        self.sSenNearestPosXL = RosAdapter.msg.coord()
      if self.sSenNearestPosXR is None:
        self.sSenNearestPosXR = RosAdapter.msg.coord()
      if self.sSenNearestPosYL is None:
        self.sSenNearestPosYL = RosAdapter.msg.coord()
      if self.sSenNearestPosYR is None:
        self.sSenNearestPosYR = RosAdapter.msg.coord()
      if self.sBoundingBox is None:
        self.sBoundingBox = []
      if self.u1MovingSt is None:
        self.u1MovingSt = 0
    else:
      self.u8Dist = 0.
      self.u8NearestDist = 0.
      self.u8RelativeVelx = 0.
      self.u8RelativeVely = 0.
      self.u8RelativeAccx = 0.
      self.u8RelativeAccy = 0.
      self.u8HeadingAngle = 0.
      self.sSensorPos = RosAdapter.msg.coord()
      self.sNearestSensorPos = RosAdapter.msg.coord()
      self.sSenNearestPosXL = RosAdapter.msg.coord()
      self.sSenNearestPosXR = RosAdapter.msg.coord()
      self.sSenNearestPosYL = RosAdapter.msg.coord()
      self.sSenNearestPosYR = RosAdapter.msg.coord()
      self.sBoundingBox = []
      self.u1MovingSt = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB().pack(_x.u8Dist, _x.u8NearestDist, _x.u8RelativeVelx, _x.u8RelativeVely, _x.u8RelativeAccx, _x.u8RelativeAccy, _x.u8HeadingAngle, _x.sSensorPos.u8X, _x.sSensorPos.u8Y, _x.sSensorPos.u8Z, _x.sSensorPos.u4H, _x.sSensorPos.u4P, _x.sSensorPos.u4R, _x.sSensorPos.u1Type, _x.sNearestSensorPos.u8X, _x.sNearestSensorPos.u8Y, _x.sNearestSensorPos.u8Z, _x.sNearestSensorPos.u4H, _x.sNearestSensorPos.u4P, _x.sNearestSensorPos.u4R, _x.sNearestSensorPos.u1Type, _x.sSenNearestPosXL.u8X, _x.sSenNearestPosXL.u8Y, _x.sSenNearestPosXL.u8Z, _x.sSenNearestPosXL.u4H, _x.sSenNearestPosXL.u4P, _x.sSenNearestPosXL.u4R, _x.sSenNearestPosXL.u1Type, _x.sSenNearestPosXR.u8X, _x.sSenNearestPosXR.u8Y, _x.sSenNearestPosXR.u8Z, _x.sSenNearestPosXR.u4H, _x.sSenNearestPosXR.u4P, _x.sSenNearestPosXR.u4R, _x.sSenNearestPosXR.u1Type, _x.sSenNearestPosYL.u8X, _x.sSenNearestPosYL.u8Y, _x.sSenNearestPosYL.u8Z, _x.sSenNearestPosYL.u4H, _x.sSenNearestPosYL.u4P, _x.sSenNearestPosYL.u4R, _x.sSenNearestPosYL.u1Type, _x.sSenNearestPosYR.u8X, _x.sSenNearestPosYR.u8Y, _x.sSenNearestPosYR.u8Z, _x.sSenNearestPosYR.u4H, _x.sSenNearestPosYR.u4P, _x.sSenNearestPosYR.u4R, _x.sSenNearestPosYR.u1Type))
      length = len(self.sBoundingBox)
      buff.write(_struct_I.pack(length))
      for val1 in self.sBoundingBox:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.u8x, _x.u8y, _x.u8z))
      _x = self.u1MovingSt
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sSensorPos is None:
        self.sSensorPos = RosAdapter.msg.coord()
      if self.sNearestSensorPos is None:
        self.sNearestSensorPos = RosAdapter.msg.coord()
      if self.sSenNearestPosXL is None:
        self.sSenNearestPosXL = RosAdapter.msg.coord()
      if self.sSenNearestPosXR is None:
        self.sSenNearestPosXR = RosAdapter.msg.coord()
      if self.sSenNearestPosYL is None:
        self.sSenNearestPosYL = RosAdapter.msg.coord()
      if self.sSenNearestPosYR is None:
        self.sSenNearestPosYR = RosAdapter.msg.coord()
      if self.sBoundingBox is None:
        self.sBoundingBox = None
      end = 0
      _x = self
      start = end
      end += 278
      (_x.u8Dist, _x.u8NearestDist, _x.u8RelativeVelx, _x.u8RelativeVely, _x.u8RelativeAccx, _x.u8RelativeAccy, _x.u8HeadingAngle, _x.sSensorPos.u8X, _x.sSensorPos.u8Y, _x.sSensorPos.u8Z, _x.sSensorPos.u4H, _x.sSensorPos.u4P, _x.sSensorPos.u4R, _x.sSensorPos.u1Type, _x.sNearestSensorPos.u8X, _x.sNearestSensorPos.u8Y, _x.sNearestSensorPos.u8Z, _x.sNearestSensorPos.u4H, _x.sNearestSensorPos.u4P, _x.sNearestSensorPos.u4R, _x.sNearestSensorPos.u1Type, _x.sSenNearestPosXL.u8X, _x.sSenNearestPosXL.u8Y, _x.sSenNearestPosXL.u8Z, _x.sSenNearestPosXL.u4H, _x.sSenNearestPosXL.u4P, _x.sSenNearestPosXL.u4R, _x.sSenNearestPosXL.u1Type, _x.sSenNearestPosXR.u8X, _x.sSenNearestPosXR.u8Y, _x.sSenNearestPosXR.u8Z, _x.sSenNearestPosXR.u4H, _x.sSenNearestPosXR.u4P, _x.sSenNearestPosXR.u4R, _x.sSenNearestPosXR.u1Type, _x.sSenNearestPosYL.u8X, _x.sSenNearestPosYL.u8Y, _x.sSenNearestPosYL.u8Z, _x.sSenNearestPosYL.u4H, _x.sSenNearestPosYL.u4P, _x.sSenNearestPosYL.u4R, _x.sSenNearestPosYL.u1Type, _x.sSenNearestPosYR.u8X, _x.sSenNearestPosYR.u8Y, _x.sSenNearestPosYR.u8Z, _x.sSenNearestPosYR.u4H, _x.sSenNearestPosYR.u4P, _x.sSenNearestPosYR.u4R, _x.sSenNearestPosYR.u1Type,) = _get_struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sBoundingBox = []
      for i in range(0, length):
        val1 = RosAdapter.msg.point3d()
        _x = val1
        start = end
        end += 24
        (_x.u8x, _x.u8y, _x.u8z,) = _get_struct_3d().unpack(str[start:end])
        self.sBoundingBox.append(val1)
      start = end
      end += 1
      (self.u1MovingSt,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB().pack(_x.u8Dist, _x.u8NearestDist, _x.u8RelativeVelx, _x.u8RelativeVely, _x.u8RelativeAccx, _x.u8RelativeAccy, _x.u8HeadingAngle, _x.sSensorPos.u8X, _x.sSensorPos.u8Y, _x.sSensorPos.u8Z, _x.sSensorPos.u4H, _x.sSensorPos.u4P, _x.sSensorPos.u4R, _x.sSensorPos.u1Type, _x.sNearestSensorPos.u8X, _x.sNearestSensorPos.u8Y, _x.sNearestSensorPos.u8Z, _x.sNearestSensorPos.u4H, _x.sNearestSensorPos.u4P, _x.sNearestSensorPos.u4R, _x.sNearestSensorPos.u1Type, _x.sSenNearestPosXL.u8X, _x.sSenNearestPosXL.u8Y, _x.sSenNearestPosXL.u8Z, _x.sSenNearestPosXL.u4H, _x.sSenNearestPosXL.u4P, _x.sSenNearestPosXL.u4R, _x.sSenNearestPosXL.u1Type, _x.sSenNearestPosXR.u8X, _x.sSenNearestPosXR.u8Y, _x.sSenNearestPosXR.u8Z, _x.sSenNearestPosXR.u4H, _x.sSenNearestPosXR.u4P, _x.sSenNearestPosXR.u4R, _x.sSenNearestPosXR.u1Type, _x.sSenNearestPosYL.u8X, _x.sSenNearestPosYL.u8Y, _x.sSenNearestPosYL.u8Z, _x.sSenNearestPosYL.u4H, _x.sSenNearestPosYL.u4P, _x.sSenNearestPosYL.u4R, _x.sSenNearestPosYL.u1Type, _x.sSenNearestPosYR.u8X, _x.sSenNearestPosYR.u8Y, _x.sSenNearestPosYR.u8Z, _x.sSenNearestPosYR.u4H, _x.sSenNearestPosYR.u4P, _x.sSenNearestPosYR.u4R, _x.sSenNearestPosYR.u1Type))
      length = len(self.sBoundingBox)
      buff.write(_struct_I.pack(length))
      for val1 in self.sBoundingBox:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.u8x, _x.u8y, _x.u8z))
      _x = self.u1MovingSt
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sSensorPos is None:
        self.sSensorPos = RosAdapter.msg.coord()
      if self.sNearestSensorPos is None:
        self.sNearestSensorPos = RosAdapter.msg.coord()
      if self.sSenNearestPosXL is None:
        self.sSenNearestPosXL = RosAdapter.msg.coord()
      if self.sSenNearestPosXR is None:
        self.sSenNearestPosXR = RosAdapter.msg.coord()
      if self.sSenNearestPosYL is None:
        self.sSenNearestPosYL = RosAdapter.msg.coord()
      if self.sSenNearestPosYR is None:
        self.sSenNearestPosYR = RosAdapter.msg.coord()
      if self.sBoundingBox is None:
        self.sBoundingBox = None
      end = 0
      _x = self
      start = end
      end += 278
      (_x.u8Dist, _x.u8NearestDist, _x.u8RelativeVelx, _x.u8RelativeVely, _x.u8RelativeAccx, _x.u8RelativeAccy, _x.u8HeadingAngle, _x.sSensorPos.u8X, _x.sSensorPos.u8Y, _x.sSensorPos.u8Z, _x.sSensorPos.u4H, _x.sSensorPos.u4P, _x.sSensorPos.u4R, _x.sSensorPos.u1Type, _x.sNearestSensorPos.u8X, _x.sNearestSensorPos.u8Y, _x.sNearestSensorPos.u8Z, _x.sNearestSensorPos.u4H, _x.sNearestSensorPos.u4P, _x.sNearestSensorPos.u4R, _x.sNearestSensorPos.u1Type, _x.sSenNearestPosXL.u8X, _x.sSenNearestPosXL.u8Y, _x.sSenNearestPosXL.u8Z, _x.sSenNearestPosXL.u4H, _x.sSenNearestPosXL.u4P, _x.sSenNearestPosXL.u4R, _x.sSenNearestPosXL.u1Type, _x.sSenNearestPosXR.u8X, _x.sSenNearestPosXR.u8Y, _x.sSenNearestPosXR.u8Z, _x.sSenNearestPosXR.u4H, _x.sSenNearestPosXR.u4P, _x.sSenNearestPosXR.u4R, _x.sSenNearestPosXR.u1Type, _x.sSenNearestPosYL.u8X, _x.sSenNearestPosYL.u8Y, _x.sSenNearestPosYL.u8Z, _x.sSenNearestPosYL.u4H, _x.sSenNearestPosYL.u4P, _x.sSenNearestPosYL.u4R, _x.sSenNearestPosYL.u1Type, _x.sSenNearestPosYR.u8X, _x.sSenNearestPosYR.u8Y, _x.sSenNearestPosYR.u8Z, _x.sSenNearestPosYR.u4H, _x.sSenNearestPosYR.u4P, _x.sSenNearestPosYR.u4R, _x.sSenNearestPosYR.u1Type,) = _get_struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sBoundingBox = []
      for i in range(0, length):
        val1 = RosAdapter.msg.point3d()
        _x = val1
        start = end
        end += 24
        (_x.u8x, _x.u8y, _x.u8z,) = _get_struct_3d().unpack(str[start:end])
        self.sBoundingBox.append(val1)
      start = end
      end += 1
      (self.u1MovingSt,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB = None
def _get_struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB():
    global _struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB
    if _struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB is None:
        _struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB = struct.Struct("<10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB")
    return _struct_10d3fB3d3fB3d3fB3d3fB3d3fB3d3fB
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
